server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

batch:
  member:
    chunk-size: 2
    schedule: "0 * * * * *"
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG